### ISSUE TITLE
embARC CVSD fame length limitation

### ISSUE THREAD

**Issue by jordi-phonak** [foss-for-synopsys-dwc-arc-processors/embarc_audio#8]
I am currently working on a project where we would like to integrate the embARC CVSD codec into our platform. Simulation and tests work fine except from the frame-length limitation. As specified in the doc:

   “-F <frame_len> | Number of samples, must be a  multiple of 4 for encoder and  decoder, default: 256”

The frame length is defined to be a multiple of 4 samples. This is quite a blocking issue for us and might be for other people as well since the standard BT SCO HV3 packet (see section *6.5.2.3 HV3 packet* of [Bluetooth Core Specification v 5.1](https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=457080)) specifies a fixed length of 30 bytes.

How feasible would it be to slightly modify the source in order to handle those 30 sample frames?

**Comment by Fargk** [comment]
Hi @jordi-phonak ,

Firstly, We have created that restriction for better performance and code size values.
I will publish patch on that week which removes that restriction.

**Comment by Fargk** [comment]
At that moment path is in audio_dev branch, after code review, it will accessible on the master.

**Comment by jordi-phonak** [comment]
Good, I Just integrated the changes and passed the bit-true tests. Thanks!
